### ISSUE TITLE
Original Everdrive N8 doesn't work with JB Firmware v. 6.6

### ISSUE THREAD

**Issue by jengelz** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#103]
Beside my case, Smokemonster informed me several cases are reported. My original Everdrive N8 doesn't work anymore, after updating from jailbreak firmware v. 6.5 to v. 6.6. I have vertical dotted lines in the Everdrive Menu. When booting games, there is just a completely grey screen, i tested a few roms. The Everdrive N8 Cartridge still works fine in my original NES System. So the Cart is fine. On the Reddit Support Megathread, i had a comment, the N8 Pro seems to work though.
![IMG_0421](https://user-images.githubusercontent.com/47487426/110091492-c8112580-7d98-11eb-9e06-a2d4f5ee5515.JPG)
![IMG_0422](https://user-images.githubusercontent.com/47487426/110091511-ce070680-7d98-11eb-99b3-2289acdd803d.JPG)

**Comment by jengelz** [comment]
The Everdrive is on Firmware v. 1.25, the latest update from Krikzz

![EverdriveVersion](https://user-images.githubusercontent.com/47487426/110112569-36aead00-7db2-11eb-8134-0f08e3b9465e.JPG)
![IMG_0428](https://user-images.githubusercontent.com/47487426/110112573-37474380-7db2-11eb-8079-3f16b2784873.JPG)

**Comment by tjanas** [comment]
Can you try downgrading the EDN8 firmware to version 1.16? In the past, I have had various issues with EDN8 firmware after that version on a real NES front loader.

**Comment by jengelz** [comment]
Nope, even worse. I heard about going back to versions before 1.20. But in this case, no improvement. The N8 Cart with v.1.16, i've tested again beforehand on my NES Frontloader, loaded a rom, and it worked. So this screen then on the NT Mini Noir
![IMG_0430](https://user-images.githubusercontent.com/47487426/110145941-417d3800-7dda-11eb-8c29-da14a7c05f5c.JPG)

**Comment by qcretro** [comment]
I can confirm the same behavior with the original Famicom N8 on the latest FW.

**Comment by tjanas** [comment]
@jengelz @qcretro please re-test your N8 cartridges with the latest official firmware update released today https://www.analogue.co/support/nt-mini-noir/firmware/1.3

**Comment by jengelz** [comment]
Hi Terry,

A guy on Twitter reported to me, he could run the Original Everdrive N8 (so not the Pro) with yesterday’s firmware update.
I can forward you the tweet if you like.
So the bug seems to be fixed (though it is not mentioned in the changelog)

I am awaiting the Jailbreak from the newest firmware, i really like the cores,

If you still like me to do the test, i can do it for you, just let me know!

Cheers guys,

Jan

Van: Terry ***@***.***>
Verzonden: donderdag 4 mei 2023 21:58
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak] Original Everdrive N8 doesn't work with JB Firmware v. 6.6 (#103)


@jengelz<https://github.com/jengelz> @qcretro<https://github.com/qcretro> please re-test your N8 cartridges with the latest official firmware update released today https://www.analogue.co/support/nt-mini-noir/firmware/1.3

**Comment by tjanas** [comment]
Thank you, @jengelz . I will report this issue as closed, but if you have a link to the tweet, it would be greatly appreciated if you could provide it here.

**Comment by jengelz** [comment]
Hi Terry,

Here is the tweet thread:

https://twitter.com/jengelenm/status/1654154758586789889

Cheers

***@***.***
***@***.******@***.***

Van: Terry ***@***.***>
Verzonden: zaterdag 6 mei 2023 15:45
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak] Original Everdrive N8 doesn't work with JB Firmware v. 6.6 (#103)


Thank you, @jengelz<https://github.com/jengelz> . I will report this issue as closed, but if you have a link to the tweet, it would be greatly appreciated if you could provide it here.
