### ISSUE TITLE
Devil Man (jap) background graphics filled with zeros, running from SD Card

### ISSUE THREAD

**Issue by jengelz** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#105]
Check the pictures, running JB FW v. 6.6, works fine on Emulation Station with FCeux on Retroarch
![IMG_0431](https://user-images.githubusercontent.com/47487426/110199828-a4aeaf00-7e5a-11eb-825d-4f2a55a7b4df.JPG)
![IMG_0432](https://user-images.githubusercontent.com/47487426/110199836-ab3d2680-7e5a-11eb-913b-2f9cb758d964.JPG)

**Comment by GreatHierophant** [comment]
Works fine for me.  Make sure the mapper is set in the NES header to 154.  This game is the only game which uses mapper 154.

**Comment by jengelz** [comment]
Ok, so i have to adapt the header inside the rom? Because i don't see any option on the Nt Mini Noir to change this, when you run the game off of SD Card. I searched the entire menu.  Maybe with CopyNES, i'm not sure...I'm not so familiar with Headers. If you have a link or something on how to do it, would be great. Many thanks

**Comment by tjanas** [comment]
@jengelz please see https://github.com/Kitrinx/NES_Header_Repair

**Comment by jengelz** [comment]
I ran the header script. The ROM is now adapted from header 88 to 154. But now the ROM has dissapeared from my ROM list inside my NES folder on the SD Card. The Mini cannot read or recognize it  anymore...
![1st run 2](https://user-images.githubusercontent.com/47487426/110249431-5ee70900-7f76-11eb-84e3-95d0b0d97f4f.PNG)

**Comment by GreatHierophant** [comment]
You'll have to find where the script moved the ROM.

**Comment by jengelz** [comment]
You mean on my PC or on my NT Mini? The script just updated the Header of the ROM in the same folder. I did all that on my PC. I then deleted the rom on my SD Card. Then copied the updated ROM from PC to SD Card. At least that's how i understand it. I can't read or understand script (or very minor understanding) Thans for helping
