### ISSUE TITLE
Freezing and Graphic Glitches from Cartridge - Shadow of the Ninja

### ISSUE THREAD

**Issue by Arcnarenth** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#108]
Shadow of the Ninja displays graphical glitches and often freezes during the opening cutscene when played from cartridge on JB 6.6.  Controller input also appears frozen and the game is unable to be started.  

The same cartridge was tested on a top loading NES and it works as intended.  A ROM loaded through the NES core of the jailbreak appears to behave properly as well.

Demonstration video:
https://youtu.be/FjxW6jvVHFE

**Comment by whitezombie2000** [comment]
I cannot reproduce this issue with my copy Shadow of the Ninja using a real cartridge. It works with 6.6 JB and official 1.2 firmware. I successfully dumped the ROM with CopyNES using Generic MMC3 TxROM, the dumped ROM works on 6.6 JB without issue, and work on an emulator. It should be noted that the back of my cartridge says REV A.

**Comment by tjanas** [comment]
@Arcnarenth does this issue still occur for you? Does it happen every time? What settings are you using for Noir? Fully buffered, zero delay, etc?

**Comment by whitezombie2000** [comment]
I just have the default settings after flashing the firmware when I do my testing.

**Comment by Arcnarenth** [comment]
@tjanas Issue is resolved with firmware 1.3.
