### ISSUE TITLE
Battletoads cart: the game freezes on the 2nd stage

### ISSUE THREAD

**Issue by wiselinkpro** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#110]
Battletoads freezes on the 2nd stage on the Analogue NT Mini Noir jailbreak, using the rom file.  However I spoke with someone with an original NT Mini (non-noir) and he claims it works fine on his.  Maybe this is due to the latest jailbreak changes with the game who knows.  If you use the game genie code to skip level 2, the game plays fine.

**Comment by tjanas** [comment]
Can you confirm the NES header bytes are the following:
`4E 45 53 1A 10 00 70 08 20 00 00 07 00 00 00 01`

Dejitter: disabled or enabled?

**Comment by wiselinkpro** [comment]
Here's what it says in my hex editor:
4e 45 53 1a 10 00 70 00 00 00 00 00 00 00 00 00

**Comment by tjanas** [comment]
Here is the checksum for the file in the [Noir SMDB](https://raw.githubusercontent.com/frederic-mahe/Hardware-Target-Game-Database/master/EverDrive%20Pack%20SMDBs/Analogue%20Nt%20Mini%20Noir%20Jailbreak%20SMDB.txt):
**Filename**: `NES/1 US - A-F/Battletoads (USA).nes`
**SHA256**: `2cc2a9afae9b9e875f0fd2f36affb615d81ce4301dbf530336fc23add999e63d`
**SHA-1**: `b5e4af9df63361498ed54a4e71bfe01e8d1a1481`
**MD5**: `1008f948966f7acc626bb5bf70c5089a`
**CRC32**: `cfff05a1`

**Comment by wiselinkpro** [comment]
thanks now I have to figure out where to get the correct file because all the ones I've been downloading are exactly the same as what I already have

**Comment by tjanas** [comment]
Have you tried using the NES 2.0 XML Database and the NES Header Repair Tool Python Script to validate and fix your rom? See the README.

**Comment by tjanas** [comment]
If you remove the 16 byte header and checksum Battletoads, it should match [no-intro](https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=0229):

Size: 262144
CRC32: 279710DC
MD5: EEFAC97AC3B85048F3685E1623210EFB
SHA-1: D85C9FF489672534FBF61A15F8FA56FFF489A34B

NES 2.0 XML Database:
```
	<game><!-- Licensed North America\Battletoads.nes -->
		<prgrom size="262144" crc32="279710DC" sha1="D85C9FF489672534FBF61A15F8FA56FFF489A34B" sum16="18CC" />
		<rom size="262144" crc32="279710DC" sha1="D85C9FF489672534FBF61A15F8FA56FFF489A34B" />
		<chrram size="8192" />
		<pcb mapper="7" submapper="2" mirroring="H" battery="0" />
		<console type="0" region="0" />
		<expansion type="1" />
	</game>
```

**Comment by wiselinkpro** [comment]
In that case my ROM must be bad, I'm getting an entirely different CRC32 than that after removing the first 16 bytes.  Which rom set is your battletoads from? Apparently mine originated in goodnes.

**Comment by wiselinkpro** [comment]
just deleted my comment because now I have a matching CRC to your last post.  I'll try it out.

**Comment by wiselinkpro** [comment]
yup it froze but now I have the correct header

**Comment by tjanas** [comment]
Is the Dejitter enabled or disabled?

**Comment by wiselinkpro** [comment]
It was disabled.  I enabled it and got a little further then it froze again.

**Comment by wiselinkpro** [comment]
I'm guessing this game only works on the original Analogue NT Mini jailbreak, not the noir.

**Comment by Ulisses-Medeiros** [comment]
when you speak in stage 2, is it the one who goes down the rope? If yes, I got to the part of the bike and without any freezing, if possible specify the version of the jailbreak and the quality of the micro sd used

**Comment by GreatHierophant** [comment]
Battletoads (USA) works OK in jailbreak v6.5.  If you wish to play it in v6.6, you can use the warp at the beginning of stage 1 to bypass stage 2 completely and get to stage 3.  The game does not appear to crash except for stage 2, and it does not crash in Battletoads (Japan) or Battletoads (Europe) on stage 2.

**Comment by wiselinkpro** [comment]
Ok thanks, I wonder if they will fix it in v6.7 or whatever version they come out with next.  I'll have to check and see if I have the europe version on there and run that instead.

**Comment by wiselinkpro** [comment]
Europe version is worse. The only one that plays good is Japan but half the text is in Japanese.

**Comment by tjanas** [comment]
Hopefully the next Noir firmware squashes all of these outstanding issues without regressions. Maybe having smaller but more frequent firmware updates would be a good thing.

**Comment by wiselinkpro** [comment]
Wow I posted about this clear back in March and nothing has been done since February.  Tsk... oh well maybe by 2025 there will be an update.

**Comment by wiselinkpro** [comment]
Nevermind on this.  Ti released a rom hack which fixes all the bugs in this game.  I'm playing it right now it works 100% flawless on current jailbreak fw.

**Comment by tjanas** [comment]
Reopening; just because a rom hack exists that works around the issue, it doesn’t fix the issue with the actual cartridge.

**Comment by wiselinkpro** [comment]
Good enough for me I closed it.  After all I don't even own one cartridge, not even the everdrive.  Been almost a year since an update, doesn't look like anything is happening.  It's fine.  Everything I want works.  Coleco was a damn good bonus, too.  Sold all my Coleco systems and games.

**Comment by whitezombie2000** [comment]
@tjanas Was the bug reported to Analogue Support or do the devs hang out in that channel? I was going to test this on a real cart to see what firmware it happened on. I'm assuming by the date it was 1.2 official or 6.6 JB since 1.2 was released Feb 22, 2021.  Was also curious if the bug is present in the older 1.0 or 1.1 firmware on a real cart.

**Comment by tjanas** [comment]
I doubt that Analogue devs monitor the discord channel, it wouldn’t hurt for someone with the cart to contact Analogue Supporr directly.

**Comment by whitezombie2000** [comment]
I can confirm that this crash happens using a real cartridge with official 1.2 firmware and doesn't crash with 1.1 firmware. As soon as you begin Level 2 Wookie Hole, the crash will occur, it maybe instant, or it may take about 10 seconds. It did the same thing on 6.6 JB firmware after I dumped the ROM with CopyNES using AxROM. I ran the ROM and it crashed at the same point. I will email Analogue Support with a description of this issue.


![Battletoads1](https://user-images.githubusercontent.com/23583562/154335983-a17a8e27-7cd3-431c-900a-1e653967bfaa.JPG)

![Battletoads2](https://user-images.githubusercontent.com/23583562/154336002-2ffafd57-461e-4806-9107-2796e57303b4.JPG)

![Battletoads3](https://user-images.githubusercontent.com/23583562/154336025-e2d05de3-7847-4e44-a71c-f359110c9ef2.JPG)

**Comment by wiselinkpro** [comment]
Just use the ROM in smokemonster's hacks folder.  Someone already fixed all the glaring flaws in the game which are what cause it to crash.  I don't have any issues whatsoever with my Analogue NT Mini Noir any more since I found that folder on my microsd card lol.  It has been a year since they released a new fw, I'm not holding my breath.  It's fine though.  This system is pretty awesome.  I just wish it had TG16 support, then it would be perfect.

**Comment by tjanas** [comment]
It is unacceptable for a real licensed cart to crash on the Noir. The system is still far from perfect; it has regressions vs. the original Nt Mini from 2017 which could work correctly with an FDS RAM Adapter in zero-delay mode (it does not work with Noir in zero-delay mode).

**Comment by tjanas** [comment]
> I can confirm that this crash happens using a real cartridge with official 1.2 firmware and doesn't crash with 1.1 firmware. 

@whitezombie2000 please re-test with the latest official firmware update released today https://www.analogue.co/support/nt-mini-noir/firmware/1.3

It should also be re-tested with the future JB firmware.

**Comment by wiselinkpro** [comment]
Cool thanks for the heads up. I wonder when jailbreak will be released and if it will include anything new.

Sent from my iPhone

On May 4, 2023, at 12:55 PM, Terry Janas ***@***.***> wrote:

﻿

I can confirm that this crash happens using a real cartridge with official 1.2 firmware and doesn't crash with 1.1 firmware.

@whitezombie2000<https://github.com/whitezombie2000> please re-test with the latest official firmware update released today https://www.analogue.co/support/nt-mini-noir/firmware/1.3

It should also be re-tested with the future JB firmware.

**Comment by whitezombie2000** [comment]
I can confirm this no longer an issue with Battletoads. I was able to get though Level 2 Wookie Hole with no freezes on v1.3 firmware.
