### ISSUE TITLE
Feature Request: Add ability to dump Metal Storm re-release cartridge

### ISSUE THREAD

**Issue by Bohman-Timothy** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#112]
The Metal Storm re-release by Retro-Bit is a new translation of the Japanese version of the game, which has some notable differences from the original English localization. I want to dump a ROM of this specific version, if possible.

According to a review article at https://nerdlypleasures.blogspot.com/2020/01/product-review-retro-bits-metal-storm.html, for the re-release of Metal Storm, "The retro-bit PCB uses the same ASIC as the large COOLBOY and MINDKIDS multicarts, emulated as NES 2.0 Mapper 268." The author of the article goes into greater detail about how the data is stored and accessed. If the statements in this article are accurate, could support for dumping those multicarts be added at some point? Or more directly, could support for dumping the Metal Storm re-release be added? I tried dumping the game by using the basic "Generic MMC3 TxROM.BIN" plugin, which did not work, and I don't see any good alternative CopyNES plugins to try, judging by their filenames.

**Comment by PizzaCube** [comment]
i have been trying to get my old save files off of both startropics games going down the list of plugins none of them worked yet.

**Comment by tjanas** [comment]
@Bohman-Timothy @PizzaCube Please re-test with JB6.7 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB
