### ISSUE TITLE
Feature Request: TurboGrafx-16 core

### ISSUE THREAD

**Issue by mikoyv3** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#114]
Because both the Analogue NT Mini Noir and upcoming Analogue Duo have Cyclone V FPGA. It would be amazing if the TurboGrafx-16 core be made available on the  NT Mini Noir

**Comment by tjanas** [comment]
I would strongly bet against this happening for various reasons.

**Comment by wiselinkpro** [comment]
this would be very great, honestly.  I just don't know if the author of the jailbreak has a PCE/TG16 core for this FPGA or not is the thing.

**Comment by PizzaCube** [comment]
i would take it...  

but i am just going to buy the FPGA turbo duo they are making anyway...   So i dont think they are going to do that.  i am shocked there is a sega on the nt mini that i never use because i have a mega sg....
