### ISSUE TITLE
Feature request - Add Hash/CRC32 or better yet an auto mapper detection in CopyNes Mini

### ISSUE THREAD

**Issue by MrCyberion** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#115]
Feature request - Add Hash/CRC32 or better yet an auto mapper detection in CopyNes Mini

Would it be possible to auto detect the correct mapper for the game we try to dump? (A function similar to the Retron 5? If I'm not mistaken the mapper is auto detected and the rom dumped automatically before running the emulator?).

If not possible, showing on screen the Hash/CRC32 and size of the rom file we just dumped would be useful to verify if we selected the right BIN file, because we currently have to select one (which is not always obvious to find), shut down the console, connect the SD card to the computer, check the CRC32/MD5, if it doesn't match any known dump we have to do all the steps again (sometimes I dump the game using multiple BIN just in case before connecting the SD card to the computer, but this process is cumbersome).

Thank you!

**Comment by tjanas** [comment]
I think CopyNES showing the crc32 of the dumped rom is a good idea. I doubt any new features will come to Nt Mini. Just be hopeful for any future firmware updates.
