### ISSUE TITLE
mapper198 video glitches

### ISSUE THREAD

**Issue by TreeSpring** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#117]
The Sinicized Tenchi Wo kurau II - shokatsu Koumei den runs image scrambling in mapper198
![IMG_4674](https://user-images.githubusercontent.com/61536259/114831900-79779200-9e00-11eb-9da9-b4568d0fef3c.JPG)
[Change to nes suffix.txt](https://github.com/SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak/files/6316174/Change.to.nes.suffix.txt)

**Comment by tjanas** [comment]
What file is this? Whatever it is, it is not the correct version of these:
```
Name: Tenchi o Kurau II - Shokatsu Koumei Den (Japan) (Rev 1).nes
Size: 524304 bytes (512 KiB)
CRC32: A109B36A
SHA256: B1171C571F794781F73EA01E4840DAE967694A5E880D545676203AA012EC72C3
SHA1: FFDCD0D879BD963C5C26EB04BC78A4996F026329
MD5: 4F3FFEA5867C5FADE8F94636346C48E0
```
```
Name: Tenchi o Kurau II - Shokatsu Koumei Den (Japan).nes
Size: 524304 bytes (512 KiB)
CRC32: D27122E5
SHA256: 595F80FEBFC53A7A3698B5F5A98F565D800FD7BB87FBB5E62CF5BC16C628F968
SHA1: CC1C05408DAFA5C1BBB9CB7675AABF47E167D747
MD5: 9AB2CF240699E521655A1FE9AA794404
```
