### ISSUE TITLE
Core Loading Error! on all cores except NES 

### ISSUE THREAD

**Issue by 1kimota** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#121]
I have a feeling this is due to a Bios issue but the README.txt tells me to look in Bios folder for instructions and the Bios folder tells me to look at the README.txt, is there something I am missing?

**Comment by eltees** [comment]
Bios files should be present in the /BIOS/ folder with the default names mentioned in the release notes for each core, though typically you can also manually go to the settings after loading a given core and open the file browser to select a specific bios there to over-ride the default (useful if you want to swap between the 'normal' GB bios and the faster loading / non scrolling super gameboy bios for the gb core, etc)

**Comment by 1kimota** [comment]
Sorry to sound frustrated but the /bios/ folder only has one file, a readme that states the bios info has been moved to the README.txt, the README.txt states to look in the bios folder.  The README.MD states instructions listed below with nothing below.

**Comment by eltees** [comment]
You need to track down the bios files yourself as they are not included in the jailbreak.

Once you have sourced the bios for a system you would like to try, you should be able to find the default file name for it (often slightly different) rename it, and then place it in the /BIOS/ folder of the sd card.

**Comment by 1kimota** [comment]
Alright so I did that and sorry for my ignorance but how do I rename it.  I am unsure what you mean by "default file name"?

**Comment by eltees** [comment]
Each core lists in its release notes the default file name it is intending to load from the /BIOS/ directory, so for example from the notes on the Atari 7800:

This core needs a BIOS to run which you can select with Core Options. The Core will load the file 7800bios.bin (expected CRC32: 5D13730C) found in the /BIOS/ directory by default.

So if your atari 7800 bios is named something different, you can either rename the file to match the expected default name, or you can go to the settings after loading that core and manually select it to load the other filename if you prefer.

**Comment by 1kimota** [comment]
ah so maybe not a BIOS problem core will not load at all, if I choose NES core it brings me to file navigation menus etc but if I choose Genesis it gives a core loading error!

**Comment by eltees** [comment]
In following the install guide on the main page, did you extract the sd card file structure for step 2 from the zip file to the root of the SD card? That should have placed all of the necessary data in the right places to launch each of the provided cores.

**Comment by 1kimota** [comment]
Yes, I am able to run NES games fine.  All the others give a core loading error!

**Comment by 1kimota** [comment]
Also thank you for looking at this with me! Your time is appreciated!

**Comment by 1kimota** [comment]
The  folder that was unzipped to root needed to be deleted. The files needed to be in root. Problem solved!

**Comment by MadeBetter** [comment]
I updated the instructions for this and created a pull request, because many people seem to have the same issue due to misleading instruction.
