### ISSUE TITLE
Why cant it autosave the SRAM?

### ISSUE THREAD

**Issue by PizzaCube** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#122]
is there some reason the Super NT nt mini and mega SG jailbreak cant auto save ram and we have to go back to the menu every time to write save game files in RAM to the SDcard?

i notice the flashcarts i have can do this every time you save in the game and it functions just like the cartridge and the user does not have to do anything

even if it auto didi this every 5 minutes or something that would be since.

**Comment by tjanas** [comment]
Flash carts typically have battery-backed SRAM that is flushed to SD card at some deterministic time. This is done to minimize wear and tear to an SD card. MiSTer does the same thing.
