### ISSUE TITLE
CopyNESmini Restore save files to cart?

### ISSUE THREAD

**Issue by PizzaCube** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#129]
do any of the CopyNESmini/CopySNES   have a way to restore the copied save files to the cart? 

you can extract but i see no way of putting them back after you change the battery.

**Comment by tjanas** [comment]
Unfortunately, no. I think other devices do have that functionality.

**Comment by PizzaCube** [comment]
ya i seen some but they are like $70  if the ntmini super nt and mega SG could do it by the jailbreak it would save me $70.. i dont really need the PC connectivity

**Comment by lesserkuma** [comment]
I also wish this was possible.

**Comment by RenEH01** [comment]
Was this feature ever implemented?

**Comment by tjanas** [comment]
No
