### ISSUE TITLE
Controllers swapped in Odyssey 2 core

### ISSUE THREAD

**Issue by JindoFox** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#132]
The core works well, but the left and right controllers are reversed, which makes it a minor hassle to play a one-player game, other than those with the right player as default (Alien Invaders, UFO). An option to swap controllers under "core options" would be appreciated. 

I'll bet this is because "Alien Invaders - Plus!" -- the first game in an alphabetical list -- uses the right controller by default.

**Comment by tjanas** [comment]
@JindoFox if this is still an issue with JB6.7, please open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB

**Comment by tjanas** [comment]
Per JB6.7 changelog:
- Improved: Odyssey^2 controllers swapped
