### ISSUE TITLE
6.6 Jailbreak caps NES ROM directory listing at ~800 items

### ISSUE THREAD

**Issue by aarongeorge** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#134]
Hi I've just updated my Firmware to the latest version (copied the directory structure zip and extracted that to the root of the SD) and copied my NES ROM set to the NES directory. It seems on the NT Mini Noir that when I browse that directory I can only see ~800 items instead of ~3000

Any ideas what might be happening?

Thanks

**Comment by tjanas** [comment]
I recommend using the file directory structure here, which generally breaks up directories to contain no more than a few hundred files. https://github.com/frederic-mahe/Hardware-Target-Game-Database/blob/master/EverDrive%20Pack%20SMDBs/Analogue%20Nt%20Mini%20Noir%20Jailbreak%20SMDB.txt

**Comment by aarongeorge** [comment]
Thanks @tjanas that worked perfectly. If the Jailbreak can't handle reading really large directories do you think it should be pointed out in the readme?

**Comment by tjanas** [comment]
Yes, it should be stated in the README. I’d like to know if it’s always the same maximum.
