### ISSUE TITLE
Four Score 'blipping' all inputs on players 3&4

### ISSUE THREAD

**Issue by eltees** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#135]
It seems like this happens both coming out of the menu and when first launching either a cartridge or rom from the NES core when Four Score is enabled.

On launching a cart its as if players 3/4 are holding start down, until they actually press start and then it clears and things run normally.  On entering or leaving the menus it's like every input on players 3/4 is pressed briefly, and then reset.

I've seen it on micro mages both cart and rom most notably where it skips through everything until the code-entry, as player 3/4 are considered to be holding 'start', but also seeing side-effects on other roms where player 3/4 start and select isn't disabled and even in the built-in controller test app where you can see all the inputs for controllers 3 and 4 light up every time you go in/out of the menu with four score input enabled and controllers connected.

The famicom 4 way input does not seem impacted in the same way, just the four score.

Attaching a video of the controller test coming out of the menu with the four score input enabled.

https://user-images.githubusercontent.com/83093307/117901366-6ed9dc80-b288-11eb-9385-7bfff10db5da.mp4

**Comment by eltees** [comment]
Wanted to attach another quick video showing the impact of that p3/p4 input glitch in-game with Micro Mages running from the cart.  The game is coded to work with both four score and fami 4 player input, but you can see the 'glitch' toggling inputs for player 3 and 4 causing unwanted character movement each time you return from the menu in four score mode, with no issues doing the same from fami 4 player input.

Other games where p3/p4 are 'allowed' to input start/select commands those can toggle as well when returning from the menu, pausing/unpausing the game or doing other unpredictable inputs.

There are additional issues booting Micro Mages when already in four score mode, as the unwanted p3/p4 controller input on start causes the intro and menu to be bypassed, but you can work around that via only plugging in the 3rd and 4th player controllers after the game has already started (or toggling four score enabled only once the game has started)

https://user-images.githubusercontent.com/83093307/118016917-37fcd880-b313-11eb-8e8d-b267853da86f.mp4

**Comment by tjanas** [comment]
Have you reached out to the analogue channels on [this Discord](https://discord.gg/UDu5ztY) so Kevtris and other end-users could see the issue and possibly chime in?

**Comment by eltees** [comment]
Didn't get much traction there unfortunately but yes.  It seems to be endemic to how the four score is being handled in the fpga where it looks like its being reset/reinitialized much more than it should be (every menu action, and potentially repeatedly at boot until all 4 pads provide manual input)

**Comment by tjanas** [comment]
Apparently this is fixed in today’s official firmware update. Please re-test @eltees

**Comment by eltees** [comment]
So behavior is overall much improved in most cases described above.  Opening/closing menus specifically no longer triggers errant inputs on players 3/4 and you can see that in both the controller test and micro mages itself.

Micro Mages runs well once in 4 score mode but there is still a hiccup/glitch on initial boot.  I think player 3/4 input is still spuriously being triggered on cartridge boot.  

If I boot with only controllers in inputs 1 and 2, the game boots fine and is fully accessible, you see the intro, can select number of players, and start with no issues

If i boot with any controller in ports 3 or 4 (even if its the only one plugged in) and with the system in 4 score mode, it will still exhibit the strange behavior of skipping the intro, selecting one player, and landing you on the code entry screen (much like someone was mashing the buttons on that controller in either port 3/4 when the cart boots.

So yes overall much improved, no more problems when actually running a game within 4 score already active, but possibly still an issue on initial boot up with errant inputs on 3/4 if they are present.

**Comment by tjanas** [comment]
@eltees Please re-test with JB6.7 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB
