### ISSUE TITLE
bonk's adventure |  the floor shakes on boss fights

### ISSUE THREAD

**Issue by masterninjah** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#137]
when you get into a boss fight the floor shakes.  it's similar to the vice project doom bug.
im on the newest official firmware using an everdrive n8 pro

**Comment by PizzaCube** [comment]
this is happening in lots of games i hope it gets fixed soon.

**Comment by tjanas** [comment]
Can you provide rom and file checksums for `Bonk's Adventure (USA).nes`? The crc32 for the file itself should be 6b6d1f2d when used with an NES2.0 header.

**Comment by PizzaCube** [comment]
it is and with a real cart

**Comment by tjanas** [comment]
@masterninjah @PizzaCube please re-test your cartridges with the latest official firmware released today https://www.analogue.co/support/nt-mini-noir/firmware/1.3
