### ISSUE TITLE
Graphical glitches with Kirby’s Adventure PAL and Everdrive N8 Pro

### ISSUE THREAD

**Issue by lesserkuma** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#138]
Kirby’s Adventure PAL on an Everdrive N8 Pro (latest OS) seems to be broken on the latest firmware. My console is set to PAL mode. I’ve tried the 3.6V Cartridge IO option and all buffer modes (fully buffered, zero delay, single buffer), but none of these fix it. No difference between old iNES and iNES 2.0 headers and it happens with all PAL localised versions (English, German, French).

![kirby](https://user-images.githubusercontent.com/67554470/119279500-7015ec80-bc2c-11eb-99cc-5bbede5028f6.png)

**Comment by Jeffersonian** [comment]
I can reproduce this issue with my N8 Pro on my Nt Mini Noir using firmware version 1.2 (non-jailbreak).

**Comment by tjanas** [comment]
@Jeffersonian @lesserkuma can either of you re-test with today’s firmware update?

**Comment by tjanas** [comment]
[Fixed](https://youtu.be/pPwWZ2D2Pjw).
