### ISSUE TITLE
GBC: Harvest Moon 3, major graphical glitches 

### ISSUE THREAD

**Issue by matthargett** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#14]
Similar glitches to Tigger Hunni Safari, like alpha/transparency layer isn't getting cleared. Visible during character creation screen. I can provide a screenshot, if that helps.

**Comment by matthargett** [comment]
Picture of the first screen after pressing Start button. This weird layer will remain for most of the new game wizard, and then turn blue for a few screens, then go away once in gameplay.

![image](https://user-images.githubusercontent.com/1550766/100530572-92acd880-31a8-11eb-9f65-ab5c5b9d61ce.jpg)

**Comment by tjanas** [comment]
Just tested this on the old Nt Mini and didn’t have any issues like this, so this must be a regression.

**Comment by matthargett** [comment]
Fixed for me in 6.5 update.
