### ISSUE TITLE
Feature Request: NSF Player Sequential Playback Improvement

### ISSUE THREAD

**Issue by 630216-29-2400** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#141]
Currently the NSF Player will only play a single track of what could be an .nsf "album" with several tracks which means that yopu have to manually start the following track once the current track has finished.
I'm not sure of the technicalities of this but would it be possible to add sequesntial play so that the NSF Player would automatically play all tracks in sequence?

I know that for SNES music it was a system issue so what was needed was moving from .spc files to .sp2 files but I'm hoping it's something that can be dealt within the FDS Player for .nsf files.

**Comment by tjanas** [comment]
@630216-29-2400 if this feature request is still wanted, please open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB
