### ISSUE TITLE
'Bouncing' status bar on both Flintstones NES games

### ISSUE THREAD

**Issue by mlc4050** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#143]
Present in the official v1.2 firmware and 6.6 jailbreak firmware.  Tested and present with both physical carts and iNES 1.0 Headered roms.   Issue is not present in the official v1.0 firmware.

**Comment by tjanas** [comment]
Have you tried a rom with a correct NES2.0 header (via https://github.com/Kitrinx/NES_Header_Repair)? What do you mean by physical cart? Original NES cartridge of that game?

**Comment by mlc4050** [comment]
Correct, the original NES cartridges

**Comment by imjustcalledtwobrothers** [comment]
This issue is present in lots of games. The educational Mickey Mouse games also have it, aside from all the ones already reported. It might be good to make an overall bug for what seems to be one shared issue, rather than a separate bug for every affected game.

**Comment by tjanas** [comment]
These issues should be brought up directly to Analogue as well, possibly via Twitter since there are outstanding issues with real original cartridges on official firmware. @imjustcalledtwobrothers & @mlc4050 could either/both of you tweet to them and share the link to it here?

**Comment by mlc4050** [comment]
The bouncing status bar issue is present on the Vice Project Doom cart as well, with official v1.2 firmware, not present with v1.0 firmware.   Do you guys know of other status bar issues that should be brought up to them?

**Comment by mlc4050** [comment]
https://twitter.com/MichaelRossow/status/1407841585832804354?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1407841585832804354%7Ctwgr%5E%7Ctwcon%5Es1_c10&ref_url=https%3A%2F%2Fpublish.twitter.com%2F%3Fquery%3Dhttps3A2F2Ftwitter.com2FMichaelRossow2Fstatus2F1407841585832804354widget%3DTweet

**Comment by mlc4050** [comment]
Apologies for the terseness in describing the issue. I've only seen the issue firsthand on those 3 games.

**Comment by tjanas** [comment]
@mlc4050 please re-test with today’s firmware release.
