### ISSUE TITLE
Crisis Force - distorted sprite graphics in level 3

### ISSUE THREAD

**Issue by mlc4050** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#144]
Distorted graphics  on level 3 of Crisis Force, rendering the game pretty much unplayable.  Present in the official v1.2 firmware and 6.6 jailbreak firmware. Tested on a physical cart and iNES 1.0 headered rom.

**Comment by tjanas** [comment]
Have you tried a rom with a correct NES2.0 header (via https://github.com/Kitrinx/NES_Header_Repair)

**Comment by tjanas** [comment]
@mlc4050 so was your problem bad rom headers?

**Comment by mlc4050** [comment]
When I reported the issue, I thought the NT Mini Noir was running the jailbreak 6.6 firmware.  I later found (after reporting the issue) that the console had been been backdated to the official v1.0 firmware, so I closed the issue. I didn't reconfirm if the issue is still present in the official 1.2 or jailbreak 6.6 firmware.
