### ISSUE TITLE
Little Nemo freezing (cartridge) Jailbreak 6.6

### ISSUE THREAD

**Issue by zoogderrick2** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#145]
Little Nemo freezes during initial cut scene. If I skip the cut scene It also just after loading first level when running from cartridge. However when I dump the rom from the same cartridge using CopyNES it runs fine from SD card.

**Comment by tjanas** [comment]
> Little Nemo freezes during initial cut scene. If I skip the cut scene It also just after loading first level when running from cartridge. However when I dump the rom from the same cartridge using CopyNES it runs fine from SD card.

Since the real cartridge has issues, have you reached out to Analogue via Twitter and email?

**Comment by tjanas** [comment]
@zoogderrick2 can you please re-test with the latest firmware released today?

**Comment by acidrain97** [comment]
Got through the entire sequence up to the title screen without issue. Using an ED pro though.
