### ISSUE TITLE
About the method of reading mapper198

### ISSUE THREAD

**Issue by treespring** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#147]
Can you give me a copy of the source program that runs mapper198? I'm trying to modify my game rom, please.
Please！

**Comment by tjanas** [comment]
Who are you asking? Analogue is closed-source.

**Comment by TreeSpring** [comment]
> Who are you asking? Analogue is closed-source.

The thing is, I have a game (640kb/mapper198) that I like very much, but it runs garbled on nt mini. I'd like to ask the firmware author if he can tell me what to do with mapper198. So I know how to modify my game so that it can work properly.

**Comment by TreeSpring** [comment]
![10F37490-488A-4207-A2B4-9173CFF7A512](https://user-images.githubusercontent.com/61536259/126226425-2e43bf3e-5e81-4bda-9bb2-0df15d693b66.jpeg)
