### ISSUE TITLE
[Feature] Setting to logically change Player 2's D3 Pin to D2, support Famicom controller mic input.

### ISSUE THREAD

**Issue by Jenetrix** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#149]
Add a setting in to change Player 2's P3 pin logically to a P2, to allow for use of 7-pin connector modified Famicom Player 2 Controllers.
Also, an option for detecting/processing mic input at $4017 D2 like a regular Famicom would, as opposed to using the external mic input.

Famicom Controllers (Player 1 and Player 2) can be made to function on the NES and NT Mini via replacing the internal Famicom plug by clipping the internal connector and replacing the ends with female d-sub connectors, and using the plug jacket of an OEM NES controller.

Player 1 controller already works OOB with the stock and jailbroken firmware, and P2's standard buttons work as well. Microphone input will only work correctly by adding in a setting to change the D3 to D2 because the 7-pin connector does not have access to D2, only D0/3/4. Microphone wire has been wired into D3 on these controllers as a result.

Mic Input test (mic wired to D3/Pin6):
https://user-images.githubusercontent.com/33210210/130667785-2fd2af69-fba4-4a0e-9551-434a62535268.mp4

![image](https://user-images.githubusercontent.com/33210210/130666898-31b89da0-5850-4fdf-9e33-97c91488edb9.png)
![image](https://user-images.githubusercontent.com/33210210/130666915-0b7c93e0-0034-4ac3-9629-b33c19e12345.png)
![image](https://user-images.githubusercontent.com/33210210/130666005-174b9d2c-0553-49ab-be86-8653186c22d3.png)
![image](https://user-images.githubusercontent.com/33210210/130666016-5e415a17-e05c-4f11-93f8-13bb3b3a1bfb.png)

**Comment by tjanas** [comment]
@Jenetrix if this feature is still wanted, please open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB
