### ISSUE TITLE
GBC: Pokemon Pinball Major graphics issue

### ISSUE THREAD

**Issue by ignignol** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#15]
Title screen plus all menus display as blank screens but otherwise function properly. Game seems to display fine once you are in a table.

**Comment by tjanas** [comment]
Title screen and gameplay work ok on original Nt Mini.
![1E4449AD-C2F5-48C3-B3B3-F27FE0A0B65C](https://user-images.githubusercontent.com/20304619/100423741-1bfdc700-3052-11eb-9bf5-3ae51e3bc7f4.jpeg)
![AA245962-BAB1-447A-A4E8-CC6919E4ACC6](https://user-images.githubusercontent.com/20304619/100423752-215b1180-3052-11eb-9909-0b1e32709937.jpeg)

**Comment by CheeseSodaPunch** [comment]
Here's video: https://youtu.be/a6N-NRNDxZw
SHA-256 of the rom: 7672001d4710272009df6a41e3cbada65decd56e0eb2f185cb3d59c08d33ea0e

**Comment by matthargett** [comment]
Fixed for me in 6.5 update.

**Comment by Elrinth** [comment]
Can original author please update if this is fixed. Please close the issue if it's okay. @ignignol

**Comment by ignignol** [comment]
Yes
