### ISSUE TITLE
Update NES Palette(s) / Presets

### ISSUE THREAD

**Issue by dizine** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#150]
Updated NES palette(s)/preset selection [suggestion]:

Including Nintendo’s 'official' NES palette as default and reference.

1. Nintendo [NES Classic Edition]
2. Sony [SONY CXA2025AS]
3. Composite [Digital Prime FBX]
4. PlayChoice-10 [RGB]
5. Black and White [NES Classic B&W]
6. Custom
+
7. Custom II*

*Additional Custom 'II' preset for A/B custom palettes etc would be quite useful [feature request].

NES Classic Edition, Sony CXA2025AS, PlayChoice-10 RGB, NES Classic Black and White https://emulation.gametechwiki.com/index.php/Famicom_Color_Palette

FirebrandX's Digital Prime http://www.firebrandx.com/nespalettes.html

**Comment by Firebrandx** [comment]
You don't want NES Classic as the default 'reference' palette. It is utter garbage due to anti-epilepsy measures. Just because Nintendo made it, doesn't make it reference quality. It's actually terrible and doesn't do the NTSC NES justice.
