### ISSUE TITLE
Feature request - Save states for NES

### ISSUE THREAD

**Issue by MrCyberion** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#153]
I realize that this feature request might be long to implement, but since it's not present in the list of current requests, I was wondering if it would be possible to add a save state function for the NES core?

Since the majority of the games do not have a save function (battery or password), it would be very convenient to have this function in order to practice a specific area of a game or to simply allow to save if we can't complete the whole game in one sitting.

Thank you!

**Comment by tjanas** [comment]
I would recommend using an Everdrive N8 Pro for save state functionality.
