### ISSUE TITLE
Dragon Warrior III and IV can't rip in COPYNES (JB 6.6)

### ISSUE THREAD

**Issue by FremontDZ** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#155]
This is a known issue but I didn't see it listed here in the issues so I wanted to get it on the radar. 

I've tried editing headers, triple-checking the mapper, and still can't get either game to rip correctly. DW 3 doesn't load at all (black screen) and DW 4 loads for a second, then goes all to bits (artifacts in the graphics). 

Carts play fine.

**Comment by PizzaCube** [comment]
startropics does not rip either

**Comment by Cheesemeister3k** [comment]
[SXROM.zip](https://github.com/SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak/files/10013441/SXROM.zip)
For DW3&4, use SXROM.BIN from this ZIP file adapted from nescartdb.com/plugins.

For ST, use HKROM.BIN.

**Comment by FremontDZ** [comment]
Thanks! I'll give it a try!

**Comment by FremontDZ** [comment]
@Cheesemeister3k worked like a charm, thanks so much for sharing! Glad to have "saved" my Dragon Warrior 3 characters as well as running the game off the SD card vs. the cart. Closing the issue.

**Comment by mariomadproductions** [comment]
@FremontDZ i think this issue should probably be re-opened, so other people can see the solution

**Comment by FremontDZ** [comment]
Done!

**Comment by mariomadproductions** [comment]
thanks! :)

**Comment by tjanas** [comment]
Issue should remain open until the fixes are incorporated in JB v6.7 or later.

**Comment by FremontDZ** [comment]
@Cheesemeister3k FYI - the SXROM you provided didn't actually work for Dragon Warrior 4 (it worked great for 3). In 4, it copies the game but doesn't recognize the saves. Then, when you start, the text is all gibbrish.

**Comment by Cheesemeister3k** [comment]
@FremontDZ I tried the DW4 save file functionality and it appeared to work correctly when the battery checkbox was checked.

**Comment by tjanas** [comment]
@FremontDZ @PizzaCube please create an issues at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB if the issue still exists with JB v6.7.
