### ISSUE TITLE
Can't run Genesis/SMS/GG/Coleco games

### ISSUE THREAD

**Issue by Retrobearcade** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#157]
Hello,

With the help of some people, we tried getting my Analogue NT Mini Noir to work with the consoles enumerated in the title.
I noted that NES and GBC ROMS/Cartridges work great.

- We tried with JB 6.2, 6.5, 6.6, but no dice. I tried 3 different SD cards (32-64GB Sandisk, Lexxar and Samsung), different HDMI cables;
- We even tried plugging the console in a different power outlet;
- We tried replacing the JB 6.6's core by the one from 6.2. I tried rolling back to the official firmware then back to the JBs;
- We tried adding BIOS;
- We tried different ROMS (including different file types .GEN, .BIN, .MD, .SMD;
- We tried 32Format and formatting to NTSF then back to FAT32;
- We tried playing around with the console's settings;
- We verified the CRC32 files and everything's fine.

Any ideas?

**Comment by tjanas** [comment]
I would ask in the [Classic Gaming Discord](https://discord.gg/UDu5ztY) for assistance.
