### ISSUE TITLE
G.I. Joe cartridge works on 6.2 but not anymore on 6.6

### ISSUE THREAD

**Issue by TT-Hipster1941** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#160]
Hello SmokeMonster,

I have a GI Joe : A Real American Hero NES cartridge that works perfectly on my original console but not on Analogue Nt Mini Noir V2. I've been running a couple tests to figure wich version is working

- Firmware 1.0 from Analogue works
- Firmware 1.2 from Analogue does not works
- Jailbreak Firmware 6.2 works
- Jailbreak Firmware 6.5 works with sound issues
- Jailbreak Firmware 6.6 does not works

Definition of not working : Games boots menu works, game crashes after a couple interaction on the first level.

All the tests between firmware versions have been done without moving the cartdrige to exclude false positive. Cartridge works 5 / 5 attemps on my OG NES. *I know it's a rare thing lol*

**Comment by tjanas** [comment]
Since the issue also exists with official Analogue firmware 1.2 (the latest firmware as of this post), could you contact Analogue Support and report back with their response? Maybe they will have a fix soon?

**Comment by TT-Hipster1941** [comment]
Email has been sent to support, will come back with answer. Thanks for the help.

**Comment by TT-Hipster1941** [comment]
Response from Analogue : "Thanks for the information. We have passed along the information to our development team. This will be addressed in future updates. In the meantime, please install the firmware v1.1 to avoid these issues."

NB : I haven't tested 1.1 yet and did'nt mentionned it in my email.

**Comment by whitezombie2000** [comment]
@TT-Hipster1941 I see you reported on Twitter that this game is fixed with v1.3 and that's great news! This issue should be closed now.
