### ISSUE TITLE
Dig Dug - Atari 2600 core

### ISSUE THREAD

**Issue by Anony400** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#164]
"Dig Dug needs to have the first 256 bytes zeroed out (or set to all FF's) so that the extra RAM can be detected properly."

I don't understand what this means. Could someone provide details on how to do this? It's the only game I can't get to work on NT Mini Noir.

**Comment by tjanas** [comment]
Open the [file](https://datomatic.no-intro.org/index.php?page=show_record&s=88&n=0121) in your favorite hex editor like [HxD](https://mh-nexus.de/en/hxd/) and set the first 256 bytes to 0xFF.
![image](https://user-images.githubusercontent.com/20304619/219135231-0fdaf637-7e5d-47be-80a2-a3d8c43feaf5.png)

**Comment by Anony400** [comment]
Thank you so much! It works.
