### ISSUE TITLE
Gameboy Core run speed

### ISSUE THREAD

**Issue by jamielovesgames** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#167]
I have a weird case with the GB core on jailbreak 6.6. I know that a real GB usually runs at a frame rate of 59.7275Hz. And the Analogue NT Mini Noir v2 running a GB core is supposed to be 60Hz over HDMI. However, I loaded R-Type on both and my GB Pocket seems to be running faster (the intro sequence eventually gets ahead on the real hardware.)

I'm a speedrunner and trying to get a sense of where my NT is at frame rate wise. It seems that I'm losing a second every 5 minutes or so. Someone on the Classic Gaming Discord compared it to the Pocket GB Core and found the NT to be running a few frames slower.

So...I would be grateful to have the current GB core on the Noir at some point in the future :)

**Comment by GreatHierophant** [comment]
The Noir is running the GB Core at 60.0988Hz like a Super Game Boy 2 with analog output and 60Hz via HDMI.
