### ISSUE TITLE
NES Karnov screen mirroring.

### ISSUE THREAD

**Issue by NightSprinter** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#168]
So, for some reason my cartridge dump of Karnov is being read as if it has vertical mirroring (the game uses horizontal).  The rom is a clean dump, and it's been checked in puNES (and I even changed the mirroring in the header which does duplicate the issue).  Any reason for this?

**Comment by tjanas** [comment]
This repository is deprecated for the Noir JB. Please open your issue here: https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB
