### ISSUE TITLE
GB & GBC: Super Mario Land has incorrect audio

### ISSUE THREAD

**Issue by thedrdodo** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#20]
Go the ending of any level. The victory music that plays is very far removed from how its supposed to sound on real hardware. Issue on nt mini noir with JB firmware 6.2. Audio issue is the same on the GB and GBC core. I compared against same rom through a SGB2 on a Super Nt.

**Comment by BooBerry** [comment]
Can confirm this.

It sounds way off to how it sounds on a) a real Game Boy, b) the Super Game Boy and c) Super Game Boy core on the SD2SNES Pro.

**Comment by thedrdodo** [comment]
Issue seems fixed to my ears in 6.5
