### ISSUE TITLE
Weird scaling presets in the Gamate core

### ISSUE THREAD

**Issue by john-098** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#24]
There is only one scaling preset for the height in the Gamate core ("2.0x" ~ 1024px) and it is wrong!! 1024px = 6,74 * 152px, the Gamate's original resolution.

**Comment by john-098** [comment]
Also, you cannot horizontally center the screen in the Width & Height settings pane.

**Comment by Firebrandx** [comment]
Probably an oversight as 7 * 152 = 1064. Horizontal centering has been an issue for several cores due to how the scaler works. It tends to shift to the right as you scale the picture upwards, making it impossible to center the image on several cores.

**Comment by tjanas** [comment]
@john-098 please re-test with JB6.7 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB
