### ISSUE TITLE
Famicom Keyboard with Family Basic input wrong keys

### ISSUE THREAD

**Issue by Elrinth** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#26]
When using the famicom keyboard and the original cartridge Family Basic with a normal Famicom. The keyboard inputs the keys you press.

But when pressing keys when having it connected to the Analogue Nt Mini Noir with jb (didn't try without jb) it will wrongly input keys a bit more to the right. Example: I press A, however it inputs into the game a D. No key is correctly mapped.

Any clue why this happens on the NT but not on an original Famicom?

Has anyone else this problem?

**Comment by tjanas** [comment]
Did you enable controller passthrough mode? It is required to use the Famicom Keyboard.

**Comment by Elrinth** [comment]
You are correct, this is a non-issue once enabling key passthrough it worked! Didn't even have to reset the game.
Sad we lose the ability to get into the menues after doing that.

**Comment by frederic-mahe** [comment]
documentation fixed with 71f9982514070d614fd8ceb6a3b2c87a3848d3ec

**Comment by Elrinth** [comment]
Closing issue as there is a workaround and reason for how it works. Thank you frederic-mahe
