### ISSUE TITLE
2600 Kool aid man

### ISSUE THREAD

**Issue by ralph1011** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#27]
Glitched screen, can’t start game

**Comment by tjanas** [comment]
What are your file checksums?

**Comment by ralph1011** [comment]
I did a quick look and it all seems to match no intro from the link you provided. I’ll post it shortly.

**Comment by ralph1011** [comment]
CRC32 (No Intro): D9BD009B
CRC32 (Mine): d9bd009b

MD5 (No Intro): 534E23210DD1993C828D944C6AC4D9FB
MD5 (Mine): 534e23210dd1993c828d944c6ac4d9fb

SHA-1 (No Intro): 2F550743E237F6DC8C75C389A01B02E9A396FDAD
SHA-1 (Mine): 2f550743e237f6dc8c75c389a01b02e9a396fdad

**Comment by GreatHierophant** [comment]
Not a bug with the Nt Mini, Kool-Aid Man uses the Difficulty A switch to pause the game.  Make sure Difficulty A is checked, the game will start.

**Comment by tjanas** [comment]
Having the 2600 switches as core menu options is a nice feature of the Noir JB. With the original Nt Mini JB, you needed a controller with **L** and **R** shoulder buttons to toggle the switches.

**Comment by ralph1011** [comment]
Def a nice feature, thanks for highlighting it...and providing some hand holding. Much appreciated.

Just wondering, is there any tutorial anywhere about changing intellivison roms to the .intv2 format? It wasn’t all that clear in the faq. That or I am a complete novice and it went over my head. 

Thanks again
