### ISSUE TITLE
vs. games

### ISSUE THREAD

**Issue by acidrain97** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#33]
Ran the python script on VS. SMB and upgraded the headers to 2.0 (I guess). I'm not seeing the dip switch screen in the core options. Also how do I get the correct colors to be displayed?

**Comment by tjanas** [comment]
Can you share your full NES2.0 header (first 16 bytes of the file)?

**Comment by acidrain97** [comment]
fixed... I'm used to a everdrive/patches doing everything... First time I have ever messed with python... I'm learning. Thank you.
