### ISSUE TITLE
Enabling Four Score for 4-players and saving not persisted after restart

### ISSUE THREAD

**Issue by Jeffersonian** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#35]
Enable:
Settings > System > Hotkeys & Controllers > 4 Player Settings > Four Score

And then save settings and cycle the system.  It defaults back to “Standard Controller”.

Tested on stock firmware, but it is probably there in the jailbreak firmware too.

**Comment by tjanas** [comment]
This is intentional.
