### ISSUE TITLE
GBC: Lufia - The Legend Returns won't start

### ISSUE THREAD

**Issue by Elrinth** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#39]
The game shows only blank screen after GB-logo. Tested E, U, J.

**Comment by Spazilton** [comment]
Confirmed. 
ROM CRC32 - 5BAE3C04
GBCBios CRC32 - 41884E46

**Comment by Elrinth** [comment]
Will start with new update core!

**Comment by Spazilton** [comment]
This issue has not been resolved for me with the 6.5 update. CRC of files above.

**Comment by matthargett** [comment]
Fixed for me with 6.5 update. Be sure that you overwrite the root of your SD card with the updated ZIP in addition to updating the firmware.
