### ISSUE TITLE
GBC: Pokemon Pinball - Corrupted frame during screen transitions

### ISSUE THREAD

**Issue by MP2E** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#42]
When the ball moves from the bottom of the pinball table to the top, or the top to the bottom, the screen transitions and some vertical lines can be seen. Here's a clip demonstrating the behavior https://streamable.com/leculg

I confirmed that this doesn't happen on a Game Boy Player, using Game Boy Interface High Fidelity. Can post a clip of that if wanted.

Tested on JB v6.5

**Comment by tjanas** [comment]
Please retest with JB v6.6

**Comment by tjanas** [comment]
@MP2E is this still broken with JB v6.6?

**Comment by MP2E** [comment]
Thanks for the ping, this appears to be fixed!
