### ISSUE TITLE
GBC: Barbie Pet Rescue, screen goes black 

### ISSUE THREAD

**Issue by matthargett** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#49]
After the below screen in the intro, screen goes black. Music still plays perfectly.
![3E5B5D6E-6C8A-4099-A6F1-95EA4EB43BDE](https://user-images.githubusercontent.com/1550766/102314733-c49f9800-3f27-11eb-8611-befd8ad43179.jpeg)

**Comment by tjanas** [comment]
Please retest with JB v6.6

**Comment by tjanas** [comment]
@matthargett is this still broken with JB v6.6?

**Comment by tjanas** [comment]
@matthargett is this still broken with JB v6.6?

**Comment by matthargett** [comment]
Verified fixed in JB 6.6, thanks!
