### ISSUE TITLE
GBC: Mia Hamm Soccer Shootout, gfx glitch on title screen

### ISSUE THREAD

**Issue by matthargett** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#50]
Weird glitching in the center of the screen during title screen display, artifacts remain on screen until game starts.
![A2D4ABA3-1405-436B-A81D-49DEF4446AC5](https://user-images.githubusercontent.com/1550766/102316023-02052500-3f2a-11eb-9076-8cf597aa7f5d.jpeg)

**Comment by tjanas** [comment]
Please retest with JB v6.6

**Comment by tjanas** [comment]
@matthargett is this still broken in JB v6.6?

**Comment by tjanas** [comment]
@matthargett is this still broken with JB v6.6?

**Comment by matthargett** [comment]
Verified fixed in JB 6.6, thanks!
