### ISSUE TITLE
GBC: Super Mario Bros Deluxe pallete issues

### ISSUE THREAD

**Issue by superretro2741** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#52]
![image](https://user-images.githubusercontent.com/76096011/102389710-675d2280-3fcb-11eb-8870-ad701e5d34a0.png)

**Comment by Elrinth** [comment]
supposed to look something like this:
![image](https://user-images.githubusercontent.com/224418/102460728-b6489d80-4047-11eb-9371-c926e0a61233.png)

**Comment by superretro2741** [comment]
Yeah the entire games colour is way off for some reason

**Comment by tjanas** [comment]
Please retest with JB v6.6

**Comment by superretro2741** [comment]
retested with Jb v6.6 it doesn't appear to be fixed.

**Comment by tjanas** [comment]
To confirm, you updated both the firmware and the core files (those from the SD Card System Structure)?

**Comment by superretro2741** [comment]
I wasn't aware the cores had to be updated like that with new files from the file structure, this has fixed the issue and it works perfect now.

**Comment by tjanas** [comment]
Yep it is in the README

**Comment by tjanas** [comment]
Please close the issue if it is fixed
