### ISSUE TITLE
GAMEKING: off center screen

### ISSUE THREAD

**Issue by superretro2741** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#53]
![image](https://user-images.githubusercontent.com/76096011/102389821-907db300-3fcb-11eb-901c-2199350df581.png)

Not sure what causes this or if it can be fixed happens with all games

**Comment by TreeSpring** [comment]
Yes, I have the same problem. The image can move to the right beyond the boundary, but not to the left

**Comment by TreeSpring** [comment]
![Uploading D7D80125-77A1-41AD-8344-8AA2CE39F494.png…]()
You can adjust the horizontal position
However, if you want to set it to full screen, there will be a problem. Even if it is adjusted to zero, the image will still be shifted to the right and cannot be adjusted to the left

**Comment by tjanas** [comment]
@superretro2741 Please re-test with JB6.7 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB
