### ISSUE TITLE
Vs. Tetris: unable to insert coin

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#58]
The DIP Switch Core menu option is not available when loading this rom that is padded for Nt Mini compatibility. I believe it is using correct and complete NES2.0 headers.
![F324EA7B-D6C9-4201-A648-E80127F5A1FA](https://user-images.githubusercontent.com/20304619/102555852-3e9d6180-408d-11eb-8b25-0c7757558185.jpeg)

**Comment by acidrain97** [comment]
Vs. Tetris has only 24KiB of PRG-ROM but the jailbreak will only load a ROM with 32KiB of PRG-ROM. You can add 8,192 padding bytes of 0x00 bytes (or 0xFF bytes) inserted between the header and start of the PRG-ROM to get the game to work. Vs. Gumshoe may also need padding in addition to ROM reordering (see NewRisingSun's fixes).

This was in the read me file. It may help with Vs. Tetris.

**Comment by tjanas** [comment]
I believe this was user error on my part.
