### ISSUE TITLE
Some games shown as color rectangles

### ISSUE THREAD

**Issue by edrozenberg** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#6]
Some of my titles are displaying as color rectangles when I load them.

For ex. here is how **Journey to Silius** loads when interpreted into these modern cuboids :) -

![Journey to Silius](https://user-images.githubusercontent.com/2648417/100171948-20708700-2e7c-11eb-96d0-865abe014ff5.jpg)

Another classic reinterpreted as modern art: **Balloon Fight** -

![Balloon Fight](https://user-images.githubusercontent.com/2648417/100172639-a04b2100-2e7d-11eb-8be0-362e64eb2d4f.jpg)

Most other games load fine.

Using the latest 2020-11-23 firmware (`ntmv2_firmware_verJB6.2.bin`) on Nt Mini Noir.

Tried using `Normal` speed setting for the SD card, rebooting the console several times, reinserting the SD card. Seems like a software/firmware issue of some sort, nothing to do with the console or SD card. Or maybe I need to do something to some of the game files related to headers?

Thank you for this great project and thank you for any hints on this issue!

**Comment by edrozenberg** [comment]
Was able to fix the issue by using some other version of each of the game files that didn't load properly. Also ran across some game versions which would display `Bad Header` when trying to load - was able to successfully use different versions of those also to get the title to load properly.

**Comment by sociaIism** [comment]
I'm having the same issue! I'm worried as to whether I'm using the wrong ROM set or if it's a core issue. What's strange to me is that homebrew ROMs (Battle Kid pictured below) work flawlessly, but all of my "official" ROMs (SMB 2 & 3 below) are registering objects as minimal squares. It's worth noting however that games with visual issues sound perfectly normal. Regardless, a definitive solution to this would be great.
![Battle Kid - Fortress of Peril](https://user-images.githubusercontent.com/74999587/100175780-0bf0b680-2e9d-11eb-8ab5-bc172cde60bd.jpg)
![Super Mario Bros 2](https://user-images.githubusercontent.com/74999587/100175789-0f843d80-2e9d-11eb-871d-3811c0f55344.jpg)
![Super Mario Bros 3](https://user-images.githubusercontent.com/74999587/100175797-127f2e00-2e9d-11eb-8b17-055198404202.jpg)

**Comment by sociaIism** [comment]
I was also able to fix the issue by using a different ROM pack. That being said, I'm now getting a "Bad Header!" error for a few ROMs.

**Comment by SmokeMonsterPacks** [comment]
These are very typical ROM-related issues, so I'll close this.

**Comment by edrozenberg** [comment]
> ...That being said, I'm now getting a "Bad Header!" error for a few ROMs.

I've seen this also. Try a few other versions of each of those ROMS. For 1 ROM I tried 3 different versions until I found one that worked.

**Comment by MrUNIVAC** [comment]
I had this exact same issue on practically every other ROM with the No-Intro romset. I was able to fix it by updating all of my ROMs to NES 2.0 headers. Once I did that, all of the previously “blocky” ones worked fine!

There’s a Python script you can use on a database to automate that process. Nerdly Pleasures explains how to use it in this post: https://nerdlypleasures.blogspot.com/2020/04/fixing-nes-headers-and-renaming-nes.html.

Here’s the latest XML database:
https://forums.nesdev.com/viewtopic.php?t=19940

Good luck!

**Comment by edrozenberg** [comment]
@MrUNIVAC thanks for the tips!  I suspected it was related to headers somehow but didn't have enough Retrogaming cred(its) to figure it out myself.
