### ISSUE TITLE
Top line missing in Game Gear graphics:

### ISSUE THREAD

**Issue by Firebrandx** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#64]
So this one had tricked me into thinking the scaler was bugged, but it turns out to be a different kind of bug:

The top line of graphics is blacked out, but still counts against the scaler. I confirmed it with an emulator screen grab.

**Comment by acidrain97** [comment]
Speaking of the GG core is this the same one used in the SG Mega? If so it would explain a few things.

**Comment by tjanas** [comment]
@Firebrandx can you confirm if this is fixed with the latest JB v6.6?

**Comment by acidrain97** [comment]
what PCU do you recommend? Some like a 

Triad WSU120-1000-13?

**Comment by Firebrandx** [comment]
Yeah that's the one I've ordered. Exact same specs as the shipped PSU.

**Comment by acidrain97** [comment]
> Yeah that's the one I've ordered. Exact same specs as the shipped PSU.

Got the Triad.. Don't see a difference but if it prevents problems down the road works for me. THX for the OCD settings videos. What a difference things make with the proper settings.

**Comment by Firebrandx** [comment]
This bug is confirmed fixed. Only minor non-issue is 720p vertical default centering is off (likely overlooked when coding the new firmware), but this is easily corrected by adjusting the value and saving the new settings.
