### ISSUE TITLE
Idea/proposal: create new repo for Nt-Mini-Legacy-Jailbreak 

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#65]
The existing latest JB2.0 and prior versions exist [here](http://blog.kevtris.org/blogfiles/). For completeness and preservation, copies of these firmwares could be kept in a new repo. Outstanding issues with the original Nt Mini JB firmware could be documented too. I would like to document them before I forget, and perhaps Kevtris could address them when he gets some free time down the road.

**Comment by frederic-mahe** [comment]
@tjanas if you'd create such repository under your user name, we could refer to it in the Noir README.

**Comment by tjanas** [comment]
@frederic-mahe I have created it [here](https://github.com/tjanas/Nt-Mini-Legacy-Jailbreak).

**Comment by frederic-mahe** [comment]
Thanks @tjanas I've added a link (see f7ca7ed8bb7a41ea58e78c428f6259cc8681182b)
