### ISSUE TITLE
NSF Core: Skate or Die 2 NSF Title song playing slowly.

### ISSUE THREAD

**Issue by Hybrid-Divide** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#67]
The title song on multiple Skate or Die 2 NSF files is playing slowly in the NSF core.
Only the title "Skate or Die" song is affected.  The rest of the game's music plays fine.
This NSF file is confirmed working normally in other players as well.

**Comment by tjanas** [comment]
@Hybrid-Divide Please re-test with JB6.7 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB
