### ISSUE TITLE
Issue / Request: Separate Audio Channel Panning for NSF Core

### ISSUE THREAD

**Issue by Hybrid-Divide** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#68]
Apologies if this is the wrong place for this, but I'd like to request being able to control Channel Panning in the NSF Core, separately from the NES core.

When listening to NSF files, I really like to separate the audio channels, but I'd like to be able to keep them centered for playing games.

Such settings are able to be saved independently for other cores, so this should be do-able.
Thanks for all the hard work!

**Comment by tjanas** [comment]
@Hybrid-Divide Please re-test with JB6.7 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB. Per JB6.7 changelog:
- NSF Audio Levels & Panning settings are now separate from cartridge settings
