### ISSUE TITLE
Simpsons : Bart vs. the Space Mutants does not run

### ISSUE THREAD

**Issue by mlc4050** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#78]
Tested with cart. Title screen is glitchy, and crashes after couch title screen.

**Comment by tjanas** [comment]
@mlc4050 is this still broken with the latest official firmware (or latest JB firmware)?

**Comment by mlc4050** [comment]
I just checked last night, the cart is now working with the official v1.2 firmware..  I will close the issue.
