### ISSUE TITLE
GBC Graphics glitches - Mickey's Speedway USA

### ISSUE THREAD

**Issue by Elrinth** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#82]
Mickey's Speedway USA (USA, Europe) (En,Fr,De,Es).gbc CRC32: 11763934
Nintendo Logo looks glitchy and some more splashscreen is glitchy.
Menues ingame is fine
InGame tiles looks somewhat glitchy

Footage (Unlisted video):
https://www.youtube.com/watch?v=lFGlJtdBKbI&feature=youtu.be

**Comment by tjanas** [comment]
Please retest with JB v6.6

**Comment by Elrinth** [comment]
This has been fixed.
