### ISSUE TITLE
GBC Audio Missing - Perfect Dark

### ISSUE THREAD

**Issue by Elrinth** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#83]
Bug initially found by: PixelSynth
Filename: Perfect Dark (USA, Europe) (En,Fr,De,Es,It) (Rumble Version).gbc
CRC32: 0601BEF6
Some audio is missing.

Video footage of bug here:
https://www.youtube.com/watch?v=G10Y-3y7xC8

**Comment by tjanas** [comment]
Please retest with JB v6.6

**Comment by Elrinth** [comment]
I can confirm it is working now.
