### ISSUE TITLE
CopyNES Generic MMC3 - GUN-NAC dump

### ISSUE THREAD

**Issue by onthewaveagain** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#85]
I tried to dump my original cartridge of Japanese GUN-NAC with the Generic MMC3 module. There is no battery in this game.

It worked and the ROM seems to play well. I have however noticed a weird issue during the intro. See here <img width="982" alt="GUN-NAC-210101-212351" src="https://user-images.githubusercontent.com/62063840/103446558-d3e94a00-4c78-11eb-93b3-7d8bff55fb2b.png"> I have tested the ROM with my NT mini Noir and with RetroArch (FCEUMMcore) and get this on both.
When played with my original cartridge, the text is all white.

Dumped file CRC32 : 699f675a

It seems to be very minor but I thought I would report.

**Comment by tjanas** [comment]
There is a bug with CopyNES on the current Noir JB firmware, where it will corrupt the dump of the PRG ROM portion of the nes dump.

**Comment by onthewaveagain** [comment]
It is sadly a regression then, Hopefully this will be fixed. I just tested with my jailbroken NT Mini and I don't get that glitch.

**Comment by onthewaveagain** [comment]
Fixed with JB6.6
