### ISSUE TITLE
Graphical glitches playing Star Keeper homebrew with new firmware JB6.5

### ISSUE THREAD

**Issue by SuperionApeFace** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#88]
Firmware JB6.5 has introduced graphical glitches playing Star Keeper that weren't in JB6.1.

https://user-images.githubusercontent.com/76917906/103486789-5cc5ca00-4dce-11eb-81e5-69cc44aadeed.mp4

**Comment by tjanas** [comment]
@SuperionApeFace Is this a cartridge or rom? If the latter, can you provide source information for it?
Can you retest with JB v6.6?

**Comment by SuperionApeFace** [comment]
It is a cartridge and it has been fixed in JB v6.6.  Thanks.
