### ISSUE TITLE
No button is mapped to "0" in the INTV core on the Famicom Network Controller

### ISSUE THREAD

**Issue by spspspspspsp** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#93]
Since "0" was remapped to ".", no button is mapped to 0 in the INTV core on the Famicom Network Controller.

When playing Ultimate Pong, for example, you are unable to leave the options menu because there is no key for "0".

Can "0" please be mapped to the "End" button on this controller?

**Comment by spspspspspsp** [comment]
I converted the Hand Controller Diagnostic ROM earlier and looked at the Famicom Network Controller. I confirmed that no button is mapped to "0".

Also, the "." button is mapped to Left + Left fire + 0 + Enter:

![ControllerDiagnostic](https://user-images.githubusercontent.com/75721855/106251712-a8965280-6258-11eb-8fcb-22716a5c7cc4.jpg)

**Comment by tjanas** [comment]
@spspspspspsp Please re-test with JB6.7 and if it is still an issue, open a ticket at https://github.com/analoguejb/Analogue-Nt-Mini-Noir-JB

Per JB6.7 changelog:
Improved Intellivision's third fire button is now mapped to Famicom Network Controller's 0 button for easier access, Intellivision numberpad 0 button has been remapped to Famicom Network Controller's . button
