### ISSUE TITLE
CopyNES Mini Backing up ROM but not Save Files

### ISSUE THREAD

**Issue by neworion** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#97]
I successfully made playable backups of all of my NES carts. Each rom works, even the ones I mention below with battery saves. Yet the save files themselves appear to be corrupt.

Dragon Warrior and Zelda 1 & 2 each used the MMC1 chip. While CopyNES created 3 *.sav files that were 8kb in size, they are not recognised by the NT mini noir or by Mesen NES emulator on the PC. So yes I did select the battery option while saving 😉

I tried using Jailbreak versions 6.5 & 6.6 and neither worked. I would love to get these save files backed up.

**Comment by tjanas** [comment]
Duplicate issue. See https://github.com/SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak/issues/11

**Comment by whitezombie2000** [comment]
This issue should be closed.
