### ISSUE TITLE
SD Card System Structure and prior firmware versions

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak#98]
https://github.com/SmokeMonsterPacks/Nt-Mini-Noir-Jailbreak/tree/main/firmware contains the previous firmware versions, but only contains the latest SD Card System Structure zip, which contains the binary core files associated with the latest firmware. For consistency, shouldn't the SD Card System Structure zips also be along side the previous firmware versions?

**Comment by frederic-mahe** [comment]
I've added previous versions of the SD Card File System. Let me know if that's ok.
